---
# Automatically build Docker images on changes to dev and push them to a
# Container Registry using HCL Bake file.

name: Build Docker Images

on:
  push:
    branches: ['main']
    tags: ['*']

jobs:
  generate-tag:
      runs-on: ubuntu-latest
      outputs:
        tag: ${{ steps.set-tag.outputs.tag }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Read tag from project
          id: set-tag
          run: |
            TAG=$(awk -F '\"' '/^version = /{print $2}' Project.toml)
            echo "tag=$TAG" >> $GITHUB_OUTPUT

  # Build and Publish all targets associated with specified group
  bake:
    needs:
      - generate-tag
    uses: darpa-askem/.github/.github/workflows/bake-publish.yml@main
    with:
      file: 'docker/docker-bake.hcl'
      group: 'prod'
      registry: 'ghcr.io'
      organization: ${{ github.repository_owner }}
      tag: ${{ needs.generate-tag.outputs.tag }}
    secrets:
      username: ${{ github.repository_owner }}
      password: ${{ secrets.GITHUB_TOKEN }}
